server:
  port: 0

ewm:
  service:
    name: ewm-service

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main
    username: postgres
    password: 52458
stats:
  server:
    name:
      stats-server