services:
  discovery-server:
    ports:
      - "8761:8761"
    build: infra/discovery-server


  config-server:
    build: infra/config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_LEASERENEWALINTERVALINSECONDS=10
      - EUREKA_INSTANCE_HOSTNAME=config-server

  gateway-server:
    build: infra/gateway-server
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL=20000
      - SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER=1.5
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=5000
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=10

  comment-service:
    build: core/comment-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=comment-service
      - SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL=20000
      - SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER=1.5
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=5000
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=10
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-db:5432/comment
      - SPRING_DATASOURCE_USERNAME=comment
      - SPRING_DATASOURCE_PASSWORD=comment
    depends_on:
      comment-db:
         condition: service_healthy


  comment-db:
    image: postgres:16.1
    container_name: postgres-comment-db
#    ports:
#      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=comment
      - POSTGRES_USER=comment
      - POSTGRES_DB=comment
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  event-service:
    build: core/event-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=event-service
      - SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL=20000
      - SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER=1.5
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=5000
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=10
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/event
      - SPRING_DATASOURCE_USERNAME=event
      - SPRING_DATASOURCE_PASSWORD=event
    depends_on:
      event-db:
        condition: service_healthy

  event-db:
    image: postgres:16.1
    container_name: postgres-event-db
    #    ports:
    #      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=event
      - POSTGRES_USER=event
      - POSTGRES_DB=event
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-service:
    build: core/user-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=user-service
      - SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL=20000
      - SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER=1.5
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=5000
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=10
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
    depends_on:
      user-db:
        condition: service_healthy

  user-db:
    image: postgres:16.1
    container_name: postgres-user-db
    #    ports:
    #      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  request-service:
    build: core/request-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=request-service
      - SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL=20000
      - SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER=1.5
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=5000
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=10
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/request
      - SPRING_DATASOURCE_USERNAME=request
      - SPRING_DATASOURCE_PASSWORD=request
    depends_on:
      request-db:
        condition: service_healthy

  request-db:
    image: postgres:16.1
    container_name: postgres-request-db
    #    ports:
    #      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=request
      - POSTGRES_USER=request
      - POSTGRES_DB=request
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build: stats/stats-server
    environment:
      - EUREKA_INSTANCE_HOSTNAME=stats-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL=20000
      - SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER=1.5
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=5000
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=10
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    #    ports:
    #      - "5437:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
