grpc:
  server:
    port: 0
org.apache.avro.specific.use_custom_coders: true
collector:
  kafka:
    producer:
      bootstrap.servers: "localhost:9092"
      key.serializer: "org.apache.kafka.common.serialization.LongSerializer"
      value.serializer: "ru.practicum.ewm.stats.avro.serializer.AvroSerializer"