server:
  port: 0

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:comment
    username: comment
    password: comment
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
  instances:
    user-service:
      slidingWindowSize: 20
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
    event-service:
      slidingWindowSize: 20
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true