grpc:
  server:
    port: 0
spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/main"
    username: "analyzer"
    password: 5432
analyzer:
  kafka:
    consumer:
      user_action:
        bootstrap.servers: "localhost:9092"
        key.deserializer: "org.apache.kafka.common.serialization.LongDeserializer"
        value.deserializer: "ru.practicum.ewm.stats.avro.deserializer.UserActionDeserializer"
        group.id: "analyzer-consumer"
        enable.auto.commit: false
      event_similarity:
        bootstrap.servers: "localhost:9092"
        key.deserializer: "org.apache.kafka.common.serialization.LongDeserializer"
        value.deserializer: "ru.practicum.ewm.stats.avro.deserializer.EventSimilarityDeserializer"
        group.id: "analyzer-consumer"
        enable.auto.commit: false
      poll_duration_seconds:
        user_action: 5
        event_similarity: 5