server:
  port: 0
grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
ewm:
  service:
    name: event-service

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:main
    username: main
    password: main
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
  instances:
    user-service:
      slidingWindowSize: 20
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
    request-service:
      slidingWindowSize: 20
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true